# Generated by Django 4.0.4 on 2022-05-16 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NW', 'NEW'), ('PR', 'PROCESSING'), ('DL', 'DELIVERING'), ('DN', 'DONE'), ('DE', 'DENIED'), ('CN', 'CANCELLED')], max_length=2)),
                ('billing_first_name', models.CharField(max_length=64)),
                ('billing_last_name', models.CharField(max_length=64)),
                ('billing_address', models.CharField(max_length=255)),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_province', models.CharField(max_length=255)),
                ('billing_region', models.CharField(max_length=255)),
                ('billing_zip', models.CharField(max_length=10)),
                ('billing_phone', models.CharField(max_length=13)),
                ('shipping_first_name', models.CharField(max_length=64)),
                ('shipping_last_name', models.CharField(max_length=64)),
                ('shipping_address', models.CharField(max_length=255)),
                ('shipping_city', models.CharField(max_length=255)),
                ('shipping_province', models.CharField(max_length=255)),
                ('shipping_region', models.CharField(max_length=255)),
                ('shipping_phone', models.CharField(max_length=13)),
                ('shipping_zip', models.CharField(max_length=10)),
                ('placed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=64)),
                ('stock_keeping_unit', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_enabled', models.BooleanField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_in_stock', models.PositiveSmallIntegerField()),
                ('is_enabled', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
